FROM alpine:latest AS builder

FROM arm32v7/alpine

# Add QEMU
COPY --from=builder qemu-arm-static /usr/bin

MAINTAINER EgoFelix <docker@egofelix.de>

RUN apk --no-cache add dnsmasq

EXPOSE 53/tcp 53/udp

ENTRYPOINT ["dnsmasq", "-k", "-N", "--max-cache-ttl=5", "--max-ttl=5"]
